# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, choices=[('arts and social sciences', 'Arts and Social Sciences'), ('computing', 'Computing'), ('science', 'Science'), ('business', 'Business'), ('dentistry', 'Dentistry'), ('design & environment', 'Design & Environment'), ('duke-nus', 'Duke-NUS'), ('engineering', 'Engineering'), ('law', 'Law'), ('medicine', 'Medicine'), ('music', 'Music'), ('yale-nus', 'Yale-NUS')], max_length=20)),
                ('matric_photo', models.ImageField(blank=True, max_length=1000, upload_to='photo')),
                ('is_verified_student', models.BooleanField()),
                ('profile_pic', models.ImageField(blank=True, max_length=1000, upload_to='profilepic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
