# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='is_verified_student',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
