# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160622_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='faculty',
            field=models.CharField(blank=True, choices=[('arts and social sciences', 'Arts and Social Sciences'), ('computing', 'Computing'), ('science', 'Science'), ('business', 'Business'), ('dentistry', 'Dentistry'), ('design & environment', 'Design & Environment'), ('duke-nus', 'Duke-NUS'), ('engineering', 'Engineering'), ('law', 'Law'), ('medicine', 'Medicine'), ('music', 'Music'), ('yale-nus', 'Yale-NUS')], default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='is_verified_student',
            field=models.NullBooleanField(default='Null'),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='matric_photo',
            field=models.ImageField(blank=True, default='Null', max_length=1000, upload_to='matric_photo'),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='profile_pic',
            field=models.FileField(blank=True, default='Null', max_length=1000, upload_to='profile_pic'),
        ),
    ]
