# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160622_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Null', max_length=1000, upload_to='profile_pic/'),
        ),
    ]
