# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_auto_20160622_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('arts and social sciences', 'Arts and Social Sciences'), ('computing', 'Computing'), ('science', 'Science'), ('business', 'Business'), ('dentistry', 'Dentistry'), ('design & environment', 'Design & Environment'), ('duke-nus', 'Duke-NUS'), ('engineering', 'Engineering'), ('law', 'Law'), ('medicine', 'Medicine'), ('music', 'Music'), ('yale-nus', 'Yale-NUS')], max_length=20)),
                ('major', models.TextField(max_length=100)),
                ('year_of_study', models.CharField(choices=[('year 1', 'Year 1'), ('year 2', 'Year 2'), ('year 3', 'Year 3'), ('year 4', 'Year 4')], max_length=4)),
                ('preferred_tuition_type', models.CharField(choices=[('one to one', 'One to One'), ('group tuition', 'Group tuition')], max_length=20)),
                ('preferred_schedule', models.CharField(choices=[('fixed schedule', 'Fixed schedule'), ('flexible schedule', 'Flexible schedule')], max_length=20)),
                ('description', models.TextField(max_length=10000)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tutee',
            name='matric_photo',
            field=models.ImageField(blank=True, default='Null', max_length=1000, upload_to='matric_photo/'),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default profile picture.png', max_length=1000, upload_to='profile_pic/'),
        ),
    ]
