# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160622_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='major',
            field=models.CharField(max_length=100),
        ),
    ]
